services:
  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: trips
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  trips-api:
    ports: 
      - 8000:3000
    env_file:
      - .env.local
    build:
      context: ./
      # target: dev
      # dockerfile: Dockerfile
    # environment:
       # - BUILD=dev
    volumes:
      - ./src:/workspace/src
    restart: always
    depends_on:
      - mongo
volumes:
  mongo-data:
